@echo off

SET zero="ghp_"
SET one="FDBKl"
SET two="5ddcP3"
SET three="znhsipq7"
SET four="i4"
SET five="hoismaWS4"
SET six="4C5"
SET seven="cN"
SET eight="i"

rem consider using a maths equation to mask the numbers

rem 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
rem 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

rem FDBKl5ddcP3znhsipq7i4hoismaWS44C5cNi

echo ...............................................
echo setting C:\Users\%username% ...
set my_path_clone=C:\Users\%username%

echo ...............................................
echo cd'ing into %my_path_clone% ...
cd %my_path_clone%

echo ...............................................
echo checking %my_path_clone% ...
echo %cd%

echo passed 1 ..............

echo ...............................................
rem echo the classic token is: %zero%%one%%two%%three%%four%%five%%six%%seven%%eight%

echo ...............................................
echo cloning cucu_cupboard_repo into %my_path_clone% ...
git clone https://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@github.com/DafetiteOgaga/cucu_cupboard_repo

rem echo ...............................................
rem echo cd'ing into custom_commands_win ...
rem cd %my_path_clone%\cucu_cupboard_repo\custom_commands_win\

echo ...............................................
echo setting custom_commands_win path...
set custom_commands_win=%my_path_clone%\cucu_cupboard_repo\custom_commands_win

echo ...............................................
echo checking current directory ...
echo %cd%

echo ...............................................
echo checking custom_commands_win ...
echo %custom_commands_win%

echo ...............................................
echo viewing the content of config ...
type .\cucu_cupboard_repo\.git\config

echo passed 2 ..............

echo ...............................................
echo setting xbin_windows path...
set xbin_windows=%my_path_clone%\xbin_windows

echo ...............................................
echo creating xbin_windows in %my_path_clone% ...
mkdir %xbin_windows%

echo ...............................................
echo confirming that xbin_windows is created in %my_path_clone% ...
echo %xbin_windows%

echo ...............................................
echo setting environmental variable ...
setx PATH "%PATH%";%xbin_windows%

echo passed 3 ..............

echo ...............................................
echo cd'ing into xbin_windows ...
cd %xbin_windows%

echo ...............................................
echo checking xbin_windows ...
echo %xbin_windows%

echo passed 4 ..............

xcopy %custom_commands_win% . /e

echo passed 5 ..............